# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  PE-ASOS:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/asos/_packaging/PE-ASOS/nuget/v3/index.json
    token: ${{secrets.AZURE_NUGET_PAT}}
  PE-ASOSPackages:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/asos/_packaging/PE-ASOSPackages/nuget/v3/index.json
    token: ${{secrets.AZURE_NUGET_PAT}}
updates:
  - package-ecosystem: nuget
    directory: /Dependabot/Dependabot.UnitTests
    schedule:
      interval: daily
    ignore:
      - dependency-name: "log4net"
    registries:
      - PE-ASOS
      - PE-ASOSPackages
  - package-ecosystem: nuget
    directory: /Dependabot/Dependabot
    schedule:
      interval: daily
    ignore:
      - dependency-name: "log4net"
      - dependency-name: "NUnit"
        versions: ["<3.0.0"]
    registries:
      - PE-ASOS
      - PE-ASOSPackages